### ISSUE TITLE
Error: Missing input files for rule make_snp_figure

### ISSUE THREAD

**Issue by josephhughes** [artic-network/civet#60]
I updated to the most recent version of civet and I'm now getting the following error message with the test datasets:

```
snakemake --nolock --snakefile /home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/find_snps.smk --forceall  --quiet --directory /tmp/tmpn3u0nx_2 --config catchment_str=tree_subtree_3,tree_subtree_1,tree_subtree_2,tree_subtree_4 outdir=/home5/nCov/Joseph/civet/2020-09-09-215641062 tempdir=/tmp/tmpn3u0nx_2 outgroup_fasta=/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/data/outgroup.fasta aligned_query_seqs=/tmp/tmpn3u0nx_2/post_qc_query.aligned.fasta all_cog_seqs=/home5/nCov/Joseph/civet/civet-cat/cog_alignment_all.fasta threshold=1 --cores 8
MissingInputException in line 102 of /home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/find_snps.smk:
Missing input files for rule make_snp_figure:
/tmp/tmpn3u0nx_2/snp_reports/ambiguities_tree_subtree_3.snps.txt
/tmp/tmpn3u0nx_2/snp_reports/tree_subtree_3.snps.txt
[Wed Sep  9 22:10:49 2020]
Error in rule find_snps:
    jobid: 0
    output: /home5/nCov/Joseph/civet/2020-09-09-215641062/snp_reports/tree_subtree_1.snps.txt, /home5/nCov/Joseph/civet/2020-09-09-215641062/figures/genome_graph_tree_subtree_1.png

RuleException:
CalledProcessError in line 308 of /home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/assess_input_file.smk:
Command 'set -euo pipefail;  snakemake --nolock --snakefile /home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/find_snps.smk --forceall  --quiet --directory /tmp/tmpn3u0nx_2 --config catchment_str=tree_subtree_3,tree_subtree_1,tree_subtree_2,tree_subtree_4 outdir=/home5/nCov/Joseph/civet/2020-09-09-215641062 tempdir=/tmp/tmpn3u0nx_2 outgroup_fasta=/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/data/outgroup.fasta aligned_query_seqs=/tmp/tmpn3u0nx_2/post_qc_query.aligned.fasta all_cog_seqs=/home5/nCov/Joseph/civet/civet-cat/cog_alignment_all.fasta threshold=1 --cores 8' returned non-zero exit status 1.
  File "/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/assess_input_file.smk", line 308, in __rule_find_snps
  File "/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message
```

Any advice would be very much appreciated.

**Comment by ViralVerity** [comment]
Hi Joseph! That was a bug in the new code, which I should have fixed with the latest commit. Let me know if you have any further problems

**Comment by josephhughes** [comment]
Hi Verity,

The update went fine but I'm still getting this error message:

MissingInputException in line 102 of
/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/find_snps.smk:
Missing input files for rule make_snp_figure:
/tmp/tmpihoml7vp/snp_reports/ambiguities_tree_subtree_8.snps.txt
/tmp/tmpihoml7vp/snp_reports/tree_subtree_8.snps.txt
[Thu Sep 10 12:10:17 2020]
Error in rule find_snps:
    jobid: 0
    output:
/home5/nCov/Joseph/civet/Repatriated/2020-09-10-115851599/snp_reports/tree_subtree_1.snps.txt,
/home5/nCov/Joseph/civet/Repatriated/2020-09-10-115851599/figures/genome_graph_tree_subtree_1.png

RuleException:
CalledProcessError in line 308 of
/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/assess_input_file.smk:
Command 'set -euo pipefail;  snakemake --nolock --snakefile
/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/find_snps.smk
--forceall  --quiet --directory /tmp/tmpihoml7vp --config
catchment_str=tree_subtree_8,tree_subtree_2,tree_subtree_10,tree_subtree_9,tree_subtree_3,tree_subtree_6,tree_subtree_5,tree_subtree_7,tree_subtree_1,tree_subtree_4
outdir=/home5/nCov/Joseph/civet/Repatriated/2020-09-10-115851599
tempdir=/tmp/tmpihoml7vp
outgroup_fasta=/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/data/outgroup.fasta
aligned_query_seqs=/tmp/tmpihoml7vp/post_qc_query.aligned.fasta
all_cog_seqs=/home5/nCov/Joseph/civet/Repatriated/civet-cat/cog_alignment_all.fasta
threshold=1 --cores 8' returned non-zero exit status 1.
  File
"/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/site-packages/civet-0.1-py3.6.egg/civet/scripts/assess_input_file.smk",
line 308, in __rule_find_snps
  File
"/home1/hugh01j/miniconda3/envs/civet/lib/python3.6/concurrent/futures/thread.py",
line 56, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message

**Comment by ViralVerity** [comment]
Hi,
Ah right ok, that's odd - I'm wondering if it hasn't reinstalled properly (which we were having an issue with last week) because those input files should now be in the output directory and not the temp directory where your version still seems to be looking for them. It's also working on other machines, so it sounds like an installation issue to me?

Could you try uninstalling and reinstalling to see if that helps? If you're under time pressure, using the --no-temp flag should get around this particular error.

**Comment by josephhughes** [comment]
Sorry, I always struggle when I update. It worked when I removed the civet
environment and then re-installed from scratch.

Thanks

**Comment by ViralVerity** [comment]
Ah fantastic, glad to hear it!
